# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: https://www.lib.kyushu-u.ac.jp/ja/activities/usage_ref/re
        id: re
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'https://www.lib.kyushu-u.ac.jp/ja/activities/usage_ref/re'
      - name: Show Response
        run: |
          echo ${{ fromJson(steps.re.outputs.headers)["Set-Cookie"] }}
          echo "SSESS=${{ fromJson(steps.re.outputs.headers)[Set-Cookie] }}" >> $GITHUB_ENV
          : # 改行付き echo であることに注目
      - name: Step2
        run: |
          echo "The SSESS is ${{ env.SSESS }}"
